### ISSUE TITLE
Icon Request: Inkscape and X11/XQuartz

### ISSUE THREAD

**Issue by violetbrina** [tinalatif/flat.icns#101]

**Comment by wjramos** [comment]
I submitted a pull request for Inkscape [Here](https://github.com/tinalatif/flat.icns/pull/85/files)

**Comment by mknrls** [comment]
@violetbrina i will work on the X11/XQuartz icon, shouldn't take long

**Comment by wjramos** [comment]
Personally, I'd like to see the black dulled in either of the two (maybe #505050 or #393939). As is, I think the left one looks nice, but I think the right one might look nice with the X as a red-orange

**Comment by violetbrina** [comment]
I support @wjramos comment. I like the black on white as is and then probably make the second an orange on black/grey.

**Comment by mknrls** [comment]
boom :P mix of both ideas with extra idea ![xquartz3](https://cloud.githubusercontent.com/assets/6585299/7267113/45df32ba-e883-11e4-9a5d-5fe88bbc9079.png)

**Comment by wjramos** [comment]
nice! that's looking awesome

**Comment by mknrls** [comment]
thanks :) @violetbrina this issue can be close. 
This icon will be merge in next few days.

**Comment by mknrls** [comment]
@violetbrina Issue can be closed. Merged: b7d9d9c
