### ISSUE TITLE
Icon Request: Aperture, Logic, Things

### ISSUE THREAD

**Issue by llangit** [tinalatif/flat.icns#102]
First of all, thanks for this amazing icon set! However, in order to make my dock look perfectly flat, I'm missing icons for Aperture, Logic and the task manager Things. Would be cool if these icons would make it into a future relase! Thanks.

**Comment by wjramos** [comment]
![things](https://cloud.githubusercontent.com/assets/5625810/7217662/9615f1be-e5f0-11e4-94fc-2a7efe111017.png)
How's this?

**Comment by llangit** [comment]
Looks great, thanks!

**Comment by mknrls** [comment]
@wjramos are also thinking of doing the Aperture and the Logic icon ?

**Comment by wjramos** [comment]
@mknrls Sure, I'll have to take a look at the default icons

**Comment by mknrls** [comment]
cant wait to see what you come up with, maybe i will try to tackle the logic one

**Comment by wjramos** [comment]
What do you think of the one I posted?

**Comment by mknrls** [comment]
it perfect just that the grey should be a similar grey to google camera or the same.

**Comment by wjramos** [comment]
![aperture](https://trello-attachments.s3.amazonaws.com/55387fbf2691dfd19fa86296/1024x1024/c585cbbf0875864e50b8e201b83232f8/aperture.png)
![logic](https://trello-attachments.s3.amazonaws.com/5538804014e506c49f39ebb8/1024x1024/5761cea97354dbbd6c6363e5cc107bf0/logic.png) 

What do you think?

**Comment by tinalatif** [comment]
Merged
Things: a3fec371d65d2738a2c0fb3b6b7cfc4ece0696d4
Aperture: 97f62903927702c87871e46e013178e92d2062c7
Logic: 04b8f3e7d78ce6929c6b355019aa428cf6937a53

**Comment by llangit** [comment]
Sorry for the late reply. I really like the icons! Thanks.
