### ISSUE TITLE
Feature Proposal: Apply Icon Set Script

### ISSUE THREAD

**Issue by wjramos** [tinalatif/flat.icns#111]
Would it be helpful for people if I created a runnable script to apply the full icon set to existing applications?

**Comment by mknrls** [comment]
yes. the current script needed to be updated for Yosemite :)

**Comment by wjramos** [comment]
Actually, somehow overlooked the script that is already there, so I'll try and update it and create a revert script

**Comment by mknrls** [comment]
cool :+1:

**Comment by mknrls** [comment]
@wjramos maybe a menu could be added, then you would have the choice to install or revert the icons.
Also give the option to reboot your computer when the installation is done (automate it)

**Comment by aj0strow** [comment]
@mknrls took it about as far as i can tbh, no idea how to reboot or revert. It's my only shell script longer than two or three lines, was just curious if it was possible.

**Comment by aj0strow** [comment]
@wjramos its got comments and functions, should be able to update it, or port to ruby / python / etc

**Comment by aj0strow** [comment]
I remember it has trouble with sub-folders and also cant deal with application name different from project file name, but the core logic of setting an icon is there. You generate an `.rsrc` file using tmp files from an `.icns` file, then tell the os to append that to a file. 

Presumably there's a way to un-append the `.rsrc` which would revert.

**Comment by wjramos** [comment]
@mknrls I think that's a good idea, I think it may be wise to withdraw the script until we can find a solution to back up and revert icons. I'll create a branch in my own repo to try – a good way to practice my ruby.

**Comment by mknrls** [comment]
Cool. I will do some research too and see if i found anything that could to help out.

**Comment by mknrls** [comment]
so i have been thinking... what the script should be doing
1) Backing all original icons and putting them in safe folder directory (also skip icons that already have been backup), this will assure that the icons can be reverted with no problem/issues.
2) Applying flat.icns and some what match app name to icon name (might be the reason some apps aren't picking up the new icons)
3) Double check icons have been backup and replace.

So this could be 3 scripts; backup.sh, install.sh & revert.sh or one script with menu options

**Comment by wjramos** [comment]
so, we need a file to handle file name and application aliases. the reason why many icons get missed is that it fails  to correlate names like `adobe-illustrator` with Adobe Illustrator, or `sublime-text` with Sublime Text 2/3
