### ISSUE TITLE
Icon Request: Photos

### ISSUE THREAD

**Issue by jlina09640** [tinalatif/flat.icns#120]
Just updated my Mac and found a new app called Photos now installed so we definitely need a flat icn for that too :+1:

**Comment by mknrls** [comment]
:+1:

**Comment by wjramos** [comment]
I'll work on this this afternoon ![Source](http://cdn.iphonehacks.com/wp-content/uploads/2013/07/ios7_photos_icon.jpg)

**Comment by wjramos** [comment]
![photos](https://cloud.githubusercontent.com/assets/5625810/7244732/bf8fc9b6-e794-11e4-83ca-978a3eab4967.png)

**Comment by mknrls** [comment]
Looks nice :)

**Comment by wjramos** [comment]
Any preference of the two? The diagonals fit inside the inner bounding box of the template, I could shrink the design slightly so the vertical and horizontals fit the inner bounds instead.

**Comment by mknrls** [comment]
Love the secound one better, its more vibriante. Let see what @jlina09640 thinks

**Comment by jlina09640** [comment]
I think the more saturated one is better! I'd love to see how the final outcome will look like :) :+1:

**Comment by wjramos** [comment]
![photos](https://cloud.githubusercontent.com/assets/5625810/7245726/300aa41c-e7a5-11e4-92d3-ee9c39e19f2b.png)
![photos2](https://cloud.githubusercontent.com/assets/5625810/7245727/3028435a-e7a5-11e4-9660-8489168be1b5.png)

**Comment by tinalatif** [comment]
I think the second one fits in with the rest of the set better

**Comment by wjramos** [comment]
Gotta say, I really like the way this one turned out

**Comment by mknrls** [comment]
looks awesome :)
