### ISSUE TITLE
Icon Request: PHPStorm, Android Studio, Filezilla, Skitch (by evernote), Pushbullet,Viber

### ISSUE THREAD

**Issue by alireza--noori** [tinalatif/flat.icns#127]
Hi, sorry for the long list. It would be great if you could design some amazing icons out of the apps I mentioned. It would complete my desktop amazingness :smiley: 
Thanks a lot,
Ali.

**Comment by mknrls** [comment]
will see if i can tackle some of these today :D

**Comment by wjramos** [comment]
@mknrls That looks great!

**Comment by mknrls** [comment]
@wjramos thank man :)

**Comment by alireza--noori** [comment]
OMG these icons are AMAZING!!!! thanks so much for spending time on them.
I look forward to the android studio one.
BTW, I have a question, so how can I get .icns files?. I looked at the project folder but these icons are not added there?!.

Cheers,
Ali.

**Comment by mknrls** [comment]
@alireza--noori :D thanks, i haven't added those yet to the repo. soon tho :) and still thinking about that
android studio one like i would like it to be a little different. Once that android studio on is done i add all of them at same time. 

For PHPStorm and viber options with ones you like better?

**Comment by alireza--noori** [comment]
@mknrls oh sure, thanks heaps man. 
mmmm it's hard to choose cause all of them are AWESOME haha but if I wanna pick one of them for PHPStorm I would pick the first one(top-left), for Viber I would pick the first one as well (left one).

Thanks a lot :smile:

**Comment by mknrls** [comment]
coo :D no problem man

**Comment by wjramos** [comment]
@mknrls I'm a huge fan of the FileZilla and Pushbullet ones especially

**Comment by mknrls** [comment]
:D

**Comment by alireza--noori** [comment]
@mknrls AWESOME work man!!! :smile: 
Actually I like the one you said you did for fun (2.1) haha :wink: 
Cheers for the great work!! :smiley:

**Comment by mknrls** [comment]
@alireza--noori thank mate :)

**Comment by alireza--noori** [comment]
@mknrls Plz lemme know when you updated the repo :wink: 
Cheers.

**Comment by mknrls** [comment]
@alireza--noori sure

**Comment by gilbarbara** [comment]
:+1:

**Comment by tinalatif** [comment]
All merged at b7d9d9c15d677f0516cf58268d7aa6d72061a772
