### ISSUE TITLE
Icon Request: Kaleidoscope

### ISSUE THREAD

**Issue by jameswlane** [tinalatif/flat.icns#130]
I snagged the original icon from the Resource folder for a base.
https://www.dropbox.com/s/72z5a5o6wugdd47/Kaleidoscope.icns?dl=0

**Comment by mknrls** [comment]
@jameswlane the color are the same but with a flat look to it. Let me know if there's any improvement that have to be made, if not this icon will be added to the repo in the next few days. Thanks :)
PS: the background is white so you want see the rounded square here

![kaleidoscope](https://cloud.githubusercontent.com/assets/6585299/7335199/9ef22320-eb7c-11e4-9cb5-e735c89dd276.png)

**Comment by wjramos** [comment]
![kaleidoscope](https://cloud.githubusercontent.com/assets/5625810/7335496/788b2da6-eb79-11e4-95aa-35fc403eff1e.png)

**Comment by mknrls** [comment]
@jameswlane here the second iteration me and @wjramos worked on

**Comment by jameswlane** [comment]
@mknrls @wjramos I actually like the first one. I think the blending of the colors are more aesthetically pleasing.

**Comment by mknrls** [comment]
@jameswlane i see what you mean, the only problem is that first one wont match the rest of the set, like  it isn't exactly flat design. That's the reason why the second one was created, we will try to come up with other options and see what can be done.

**Comment by jameswlane** [comment]
@mknrls You also make a very valid point. Maybe we can break it up into more than six sections and add more shades. Maybe twelve sections? Break the Red, Green and Dark Blue ( Or the three points ) into three sections themselves.

**Comment by mknrls** [comment]
@jameswlane i don't know if it's going to look right but we could try. By the way this was a iteration we had before we settle with the current one, witch is still a good option if you like it

![kaleidoscope](https://cloud.githubusercontent.com/assets/6585299/7353404/3d234910-ece1-11e4-9521-2c107bd9da5c.png)

**Comment by wjramos** [comment]
I'll do another version tonight with more sections, possibly a low-poly style

**Comment by jameswlane** [comment]
I was thinking on this maybe something mosaic or just get rid of the colors and make its a single color.

**Comment by mknrls** [comment]
@jameswlane here a new concept i came up with :)  
This is what happen when abstract and secondary colors becomes friends lol 

![kaleidoscoperemix](https://cloud.githubusercontent.com/assets/6585299/7448211/b79cad80-f1e1-11e4-9c19-8bd3cddfae19.png)

**Comment by wjramos** [comment]
![kaleidoscope](https://cloud.githubusercontent.com/assets/5625810/7509060/acc20354-f440-11e4-94bd-d23e095174b5.png)

**Comment by jameswlane** [comment]
@wjramos love the last one its gorgeous

**Comment by tinalatif** [comment]
+1

**Comment by wjramos** [comment]
![kaleidoscope](https://cloud.githubusercontent.com/assets/5625810/7532017/af3b044c-f516-11e4-9ebe-d0d533776c0f.png)
One more

**Comment by wjramos** [comment]
Let me know which you guys think

**Comment by tinalatif** [comment]
I really love the previous one (I think it's because of the more even dispersion). I'm a little concerned it might be too busy at the size of a dock icon, but I think I might like it too much to care

**Comment by wjramos** [comment]
Representing rainbow gradients in geometric shapes is pretty tough

**Comment by wjramos** [comment]
You might also notice I slightly modified the shape of the triangle.  The original icon of this App also has a swirl appearance I tried to capture with the lines of the newer shape

**Comment by jameswlane** [comment]
@wjramos I think you did a amazing job and nailed it. I agree with @tinalatif, I think it's gorgeous.

**Comment by wjramos** [comment]
![kaleidoscope](https://cloud.githubusercontent.com/assets/5625810/7580335/3f7965a8-f828-11e4-8d13-7583aa871aed.png)

**Comment by wjramos** [comment]
![kaleidoscope](https://cloud.githubusercontent.com/assets/5625810/7580654/3289c13e-f82e-11e4-87c8-b9a662ba4a12.png)
More color uniformity

**Comment by tinalatif** [comment]
merged at f368bc6555af24b175bedddef434c9ce37729feb (@wjramos I have to say, this is one of my favourite icons!)

**Comment by wjramos** [comment]
@tinalatif Thank you Tina! :)
