### ISSUE TITLE
Icon Request: Querious

### ISSUE THREAD

**Issue by jameswlane** [tinalatif/flat.icns#131]
I snagged the original icon from the Resource folder for a base.
https://www.dropbox.com/s/859yfe9q49b10bg/Querious.icns?dl=0

**Comment by wjramos** [comment]
Out of curiosity, how do you like Querious as opposed to Sequel pro?

**Comment by jameswlane** [comment]
@wjramos I actually really love it, I been using Querious 2 and its hands down been one of the best utilities I purchased for managing and working with SQL I wish they had something like it for MongoDB.

**Comment by wjramos** [comment]
![querious](https://cloud.githubusercontent.com/assets/5625810/7335890/0e59557a-eb92-11e4-88b4-02a1832da63c.png)
First draft of the icon

**Comment by jameswlane** [comment]
I like it, great conversion from 3d to flat.

**Comment by wjramos** [comment]
I've been playing with the beams a bit - they just feel unfinished in this one

**Comment by wjramos** [comment]
![querious](https://trello-attachments.s3.amazonaws.com/553932f37644fd3fb5202262/1024x1024/9aff298ff58e16060c855c5c51f33232/querious.png)

**Comment by wjramos** [comment]
I'll figure something out

**Comment by jameswlane** [comment]
Hey @wjramos I was just touching base with you to see if any update on this. I do like both icons you linked.

**Comment by wjramos** [comment]
My apologies for the delay on this one - I was hoping to get some additional feedback before I submitted a pull request - I just feel this one is a difficult icon to make feel polished like the others in the set

**Comment by tinalatif** [comment]
@wjramos I'd just simplify it. I think improvising a minimal icon that fits with the set is preferred over a more complicated but truer-to-original icon that doesn't. Maybe get rid of the white/blue capsule?

**Comment by jameswlane** [comment]
I was updating my icons today and noticed that this issue / icon is still left open. Is there any movement on this? Thank you again for making this icon.
