### ISSUE TITLE
Icon Request: Sonos

### ISSUE THREAD

**Issue by jameswlane** [tinalatif/flat.icns#132]
I snagged the original icon from the Resource folder for a base.
https://www.dropbox.com/s/5gytiy0b1v07pom/Sonos.icns?dl=0

**Comment by mknrls** [comment]
Let me know if there's any improvement that have to be made, 
if not the issue can be close and these icons will be added to the repo in the next few days. Thanks :)

![sonos](https://cloud.githubusercontent.com/assets/6585299/7334946/e6f20980-eb70-11e4-91e8-bc18206ee26a.png)

**Comment by wjramos** [comment]
Here's an alternate version I came up with
![sonos](https://cloud.githubusercontent.com/assets/5625810/7335766/2ac7aada-eb89-11e4-951c-f609f6cc3f5f.png)

**Comment by jameswlane** [comment]
@mknrls @wjramos I like the first one due to one of the big items in the Sonos logo and branding is it being palindrome.

**Comment by wjramos** [comment]
Perfect - @mknrls want to issue a pull request an yours?

**Comment by mknrls** [comment]
@wjramos i will do a pull request soon

**Comment by tinalatif** [comment]
Merged: b7d9d9c15d677f0516cf58268d7aa6d72061a772
