### ISSUE TITLE
Icon Request: Jet Brains Suite

### ISSUE THREAD

**Issue by jameswlane** [tinalatif/flat.icns#133]
I know there was some request for some of the Jet Brains IDEs

Here are some of the original .icns

PhpStorm
https://www.dropbox.com/s/ychg089ar3d919g/PhpStorm.icns?dl=0

RubyMine
https://www.dropbox.com/s/sm6x26iw4eo2xsd/RubyMine.icns?dl=0

WebStorm
https://www.dropbox.com/s/gt3y5tyqwyoi6wx/WebStorm.icns?dl=0

**Comment by mknrls** [comment]
php PhpStorm has been design and will be merge in the next few days, can viewed here #127 
rubymine and webstrom icons, will be work on in next few days or so #18 #24

**Comment by mknrls** [comment]
@jameswlane here they are, let me know if the any improvement that have to be made, if not the issue can be close and these icons will be added to the repo in the next few days. Thanks.

**Comment by jameswlane** [comment]
I like them. They are a lot more unified looking then the actual originals from jet brains. I give this a thumbs up.

**Comment by mknrls** [comment]
thank man :)

**Comment by tinalatif** [comment]
Merged: b7d9d9c15d677f0516cf58268d7aa6d72061a772
