### ISSUE TITLE
Icon Request: Mischief 

### ISSUE THREAD

**Issue by jlina09640** [tinalatif/flat.icns#134]
Hello all! I'm really happy about the awesome updates we keep giving, so let's do some more! Would absolutely love if someone made one for mischief, here's a reference from the app store:

http://a4.mzstatic.com/us/r30/Purple1/v4/7d/98/b0/7d98b00d-1b45-7fbb-fe0a-eda9796668a3/icon256.png

Awesome work everyone, keep it up! :)

**Comment by mknrls** [comment]
will work on it :D

**Comment by wjramos** [comment]
I really like the left one as someone who is unfamiliar with the app

**Comment by mknrls** [comment]
good point, like the second one too.

**Comment by jlina09640** [comment]
Woah how awesome! Definitely like the second one, too!

**Comment by mknrls** [comment]
:)

**Comment by mknrls** [comment]
@jlina09640 this icon will be add to the repo in the next few days, You can close the issue :)

**Comment by jlina09640** [comment]
@mknrls Already did! Thanks so much~
