### ISSUE TITLE
Icon request: Dolphin emulator

### ISSUE THREAD

**Issue by secrettriangle** [tinalatif/flat.icns#136]

**Comment by mknrls** [comment]
Let me know if there's any improvement that have to be made, 
if not the issue can be close and this icon will be added to the repo in the next few days. Thanks :)

![dolphin emulator](https://cloud.githubusercontent.com/assets/6585299/7334848/f7d28f7a-eb6d-11e4-9c2b-b098ccdc90db.png)

**Comment by secrettriangle** [comment]
Awesome!

**Comment by tinalatif** [comment]
@mknrls as a general rule I think issues should be kept open until they're merged in

**Comment by mknrls** [comment]
@tinalatif sorry about that.

**Comment by mknrls** [comment]
@secrettriangle was talking to @wjramos yesturday and suggested me to do a white blue version (matched the logo on the website) do you have a preference?
![dolphin emulator2](https://cloud.githubusercontent.com/assets/6585299/7337834/012665f4-ec06-11e4-94c9-3617aad569b9.png)

**Comment by secrettriangle** [comment]
@mknrls either one is fine, but I'm leaning towards the first one because it actually looks like a dolphin in water. :)

**Comment by mknrls** [comment]
@secrettriangle well well :P didnt see it like that lol but now that point it out, its make total sense haha

**Comment by mknrls** [comment]
@secrettriangle Issue can be closed. Merged: b7d9d9c

**Comment by secrettriangle** [comment]
:+1:
