### ISSUE TITLE
Icon Request: Rdio

### ISSUE THREAD

**Issue by alaskattack** [tinalatif/flat.icns#138]

**Comment by mknrls** [comment]
![rdio](https://cloud.githubusercontent.com/assets/6585299/7334794/2fdb4274-eb6c-11e4-85ec-b2b1fbab2fc4.png)

Let me know if there's any improvement that have to be made, 
if not the issue can be close and these icons will be added to the repo in the next few days. Thanks :)

**Comment by tinalatif** [comment]
Merged: b7d9d9c15d677f0516cf58268d7aa6d72061a772
