### ISSUE TITLE
Icon Request: Sublime text

### ISSUE THREAD

**Issue by Arnarkari93** [tinalatif/flat.icns#139]
Is it possible to get the icon to change also for sublime text 3 ?

**Comment by Arnarkari93** [comment]
just did it manualy

**Comment by wjramos** [comment]
I didn't realize there was a difference between 2 and 3 icons

**Comment by Arnarkari93** [comment]
Yeah it's probably because sublime text 3 is named **Sublime Text.app** while sublime text 2 is named **Sublime Text 2.app**

**Comment by wjramos** [comment]
Ah, yeah the install script needs some work
