### ISSUE TITLE
Icon Request: Microsoft Office, uTorrent, MAMP, GitTower

### ISSUE THREAD

**Issue by JustDADE** [tinalatif/flat.icns#145]
Also Google Chrome Canary

**Comment by mknrls** [comment]
@JustDADE all of them are already here. witch method did you use to install the icons?

**Comment by wjramos** [comment]
All of these icons are currently in the latest package @JustDADE

**Comment by JustDADE** [comment]
Hmm, I see it in icns folder, but for some reason install.sh do not updates it. Oh well, I'll use LiteIcon.

**Comment by wjramos** [comment]
The install.sh needs some work, it's a little outdated
