### ISSUE TITLE
Icon request: TextWrangler

### ISSUE THREAD

**Issue by gilbarbara** [tinalatif/flat.icns#149]
The original icon.
![TextWrangler](https://macin.files.wordpress.com/2008/10/textwrangler-icon.png)

**Comment by mknrls** [comment]
Will be worked in the next few days

**Comment by mknrls** [comment]
what you think? 
![textwrangler](https://cloud.githubusercontent.com/assets/6585299/7432417/f6880172-eff5-11e4-8340-9d527f460892.png)

**Comment by gilbarbara** [comment]
It's great!

Thanks @mknrls

**Comment by mknrls** [comment]
no problem @gilbarbara :)

**Comment by tinalatif** [comment]
Merged: b7d9d9c15d677f0516cf58268d7aa6d72061a772
