### ISSUE TITLE
Icon request: Cisco Jabber

### ISSUE THREAD

**Issue by nem604** [tinalatif/flat.icns#153]
I know it might not be as popular as some of the other requests, but we use Cisco Jabber at work and it drives me crazy that it's the only icon on my dock that doesn't match the rest of the theme.

Original icon from resource folder: https://www.dropbox.com/s/786rw9d1fde7hm6/Jabber.icns?dl=0

**Comment by mknrls** [comment]
no worry, all icons are welcome, this driven by the community :) i will work this icon in the next few days or so.

**Comment by nem604** [comment]
Thank you!

**Comment by mknrls** [comment]
what do you think ? :) 
![cisco jabber](https://cloud.githubusercontent.com/assets/6585299/7432409/e1c881c6-eff5-11e4-855e-92e9d25a3f15.png)

**Comment by nem604** [comment]
Looks great, thank you very much!

**Comment by mknrls** [comment]
@nem604 no problem

**Comment by tinalatif** [comment]
Merged: b7d9d9c15d677f0516cf58268d7aa6d72061a772
