### ISSUE TITLE
Icon Request: TeamViewer

### ISSUE THREAD

**Issue by alireza--noori** [tinalatif/flat.icns#157]
Once again thanks for your Awesome work :)

**Comment by ejgisbertm** [comment]
Hello everyone!

This is my first ever contribution to both this project and GitHub, so please correct me if I do something wrong.

This is TeamViewer.app original icon:
![iconlegacy](https://cloud.githubusercontent.com/assets/13053885/8413314/74aa951a-1e59-11e5-96be-48104219397e.png)

And this is one I made in replacement:
![teamviewer](https://cloud.githubusercontent.com/assets/13053885/8413331/9295e9a8-1e59-11e5-95fb-4fb3b17de027.png)

I hope it is up to expectations. One caveat however, I made it as a raster image as I do not have experience working with vectors, I could try to use an online converter (the resulting file is a .SVG, no .AI) but I can't vouch for the results.

Best regards!

**Comment by wjramos** [comment]
Recreated yours as a vector @ejgisbertm 
![teamviewer](https://cloud.githubusercontent.com/assets/5625810/8543378/4ecf2524-2451-11e5-9457-51b031fcbf62.png)

**Comment by ejgisbertm** [comment]
Great @wjramos, if @tinalatif approves the icon you can go ahead and issue a pull request, after all, you can derive the .png and .icns from the .ai file.

**Comment by tinalatif** [comment]
Looks good to me!

**Comment by tinalatif** [comment]
Merged at 4dfcaea27e92c6b33e34406fff005d451ce106a3
