### ISSUE TITLE
Icon request: Goofy

### ISSUE THREAD

**Issue by vasu** [tinalatif/flat.icns#170]
http://www.goofyapp.com/

**Comment by wjramos** [comment]
+1 Will try working on one today

**Comment by wjramos** [comment]
![goofy](https://cloud.githubusercontent.com/assets/5625810/7921393/14e6516a-085a-11e5-80d7-493c3db0d297.png)

**Comment by wjramos** [comment]
@vasu how do you feel about this one?

**Comment by wjramos** [comment]
Without feedback, PR issued #194

**Comment by tinalatif** [comment]
Merged at af2d431ec3cb5b4816cb70a4dbd172a6eade5d6e
