### ISSUE TITLE
Icon Request: LastPass

### ISSUE THREAD

**Issue by mcallinder** [tinalatif/flat.icns#176]
https://lastpass.com/

![LastPass Icon](http://a5.mzstatic.com/us/r30/Purple1/v4/eb/02/a7/eb02a7a7-7b02-89f8-bd62-e2a8eacffac5/icon256.png)

**Comment by wjramos** [comment]
I'll do this one this afternoon

**Comment by wjramos** [comment]
![lastpass](https://cloud.githubusercontent.com/assets/5625810/8018503/0e88a066-0bd4-11e5-99a3-a03f19240ac0.png)

**Comment by mcallinder** [comment]
Looks good :+1:

**Comment by wjramos** [comment]
Cool, I'll go ahead and issue a pull request when i get a chance

**Comment by wjramos** [comment]
PR issued #189

**Comment by tinalatif** [comment]
Merged at 0707619534bbc745bcfa362e43ec7a818f146514
