### ISSUE TITLE
Icon Request: Pandora

### ISSUE THREAD

**Issue by mcallinder** [tinalatif/flat.icns#178]
![Pandora Icon](http://appshopper.com/blog/wp-content/uploads/2010/05/pandora-icon.png)

**Comment by wjramos** [comment]
I guess I never realized they had a desktop app, I'll take a crack at this when I get a chance

**Comment by mcallinder** [comment]
Ya.. I was going to link to it but you need a Pandora One account to view the website. http://www.pandora.com/desktop

**Comment by wjramos** [comment]
PR issued #195 -- let me know what you think

**Comment by mcallinder** [comment]
Looks good, thanks.

**Comment by tinalatif** [comment]
Merged at 47041d16d5cdd4b2fa846091e9a1dcd9335869e9
