### ISSUE TITLE
Icon Request: Emacs

### ISSUE THREAD

**Issue by Looveh** [tinalatif/flat.icns#181]
Forked from #19

![emacs modern](https://cloud.githubusercontent.com/assets/1567752/8183532/0aa8208a-1439-11e5-9e07-a66c46d42596.png)

**Comment by TheQuantum** [comment]
+1. Additional icon: 
![icon_512x512 2x](https://cloud.githubusercontent.com/assets/10932585/8576069/f40437ec-259f-11e5-9b9c-ded71ccbdd8e.png)

**Comment by wjramos** [comment]
See PR #206

**Comment by tinalatif** [comment]
Merged at 52aaccc2a42db424f6068672d737810fe9e779a6
