### ISSUE TITLE
Icon Request: Opera

### ISSUE THREAD

**Issue by jameswlane** [tinalatif/flat.icns#183]
I snagged the original icon from the Resource folder for a base.
https://www.dropbox.com/s/mgcgtadr4z6d3xe/app.icns?dl=0

**Comment by wjramos** [comment]
Please refer to PR #193 for my attempt at this icon

**Comment by tinalatif** [comment]
Merged at 65e9b410e0c42be76c4eee66f9df9678f3b624be
