### ISSUE TITLE
need a uninstaller to restore my default icons

### ISSUE THREAD

**Issue by bboylilshaw** [tinalatif/flat.icns#184]
that would be great if you have a uninstaller to restore the default icons, incase someone want to change icons back.

**Comment by muhasturk** [comment]
In LiteIcon global menu select **Restore All System Icon**

https://yadi.sk/i/o3IYsifLiEQvq

**Comment by CreatedBySeb** [comment]
I have an uninstaller script in my PR #263, if you run the installer again then the uninstaller it'll fix all your icons.
