### ISSUE TITLE
Icon Request: Atom

### ISSUE THREAD

**Issue by joseluisq** [tinalatif/flat.icns#186]
![image](https://cloud.githubusercontent.com/assets/1700322/8482030/7de7ada2-20ac-11e5-860f-e7b1162b9463.png)

https://atom.io/

**Comment by jameswlane** [comment]
There is already one for Atom.io https://github.com/tinalatif/flat.icns/blob/master/icns/atom.icns

**Comment by joseluisq** [comment]
@jameswlane thanks. 
But I think this issue (enhancement) should remain until next version. 
Actually the current version is 1.0 :)

**Comment by tinalatif** [comment]
You're right! I haven't used Atom in a long time and didn't realize there was a new icon. I unfortunately don't have my laptop with Illustrator with me until next week, but I'll be sure to update the current icon then

**Comment by joseluisq** [comment]
Perfect!
Well, I await for next release.
Great job!

**Comment by wjramos** [comment]
I'll take a crack at this right now

**Comment by wjramos** [comment]
Pull request issued #192

**Comment by joseluisq** [comment]
:+1:
