### ISSUE TITLE
Icon Request: Netbeans

### ISSUE THREAD

**Issue by joseluisq** [tinalatif/flat.icns#187]
![image](https://cloud.githubusercontent.com/assets/1700322/8482640/9a393e22-20b0-11e5-80a6-2d7f960fd6c2.png)

https://netbeans.org/

**Comment by wjramos** [comment]
![netbeans](https://cloud.githubusercontent.com/assets/5625810/8541622/736886ee-2444-11e5-8072-397569dec4b0.png)

**Comment by joseluisq** [comment]
Cool !

**Comment by joseluisq** [comment]
I think you should send a pull request :)

**Comment by wjramos** [comment]
PR issued #196

**Comment by joseluisq** [comment]
Cool :+1:
