### ISSUE TITLE
Icon Set Request: Flat Round Icons

### ISSUE THREAD

**Issue by danielsatanik** [tinalatif/flat.icns#190]

**Comment by wjramos** [comment]
I like the idea – this should probably be an entirely separate icon set though

**Comment by wjramos** [comment]
I did just create a template for a round set - see below for example:

![folder-app](https://cloud.githubusercontent.com/assets/5625810/8538961/fbc5206c-2429-11e5-8c96-8d18e83220a2.png)

**Comment by danielsatanik** [comment]
Looks kind of good. I am searching for a flat round icon set with consistent style for a long time now. I like how the creator of the square one preserved the original coloring and still uses a consistent flat style for all the icons. I hope there will be a follow up pack with round shapes.

**Comment by wjramos** [comment]
I went ahead and made a new repo for a rounded icon set here: wjramos/circl.icns

I've done a few already, but I'd like Tina's permission before redoing too many of the icons

**Comment by wjramos** [comment]
If anyone else is interested in seeing a circle pack, please let me know

**Comment by danielsatanik** [comment]
I look forward to the complete set.

**Comment by wjramos** [comment]
for any updates regarding this, please visit my hard fork [Here](https://github.com/wjramos/circl.icns)

**Comment by tinalatif** [comment]
@wjramos Looks good! I'm fine with it. If you're going to be using the original files, I'd appreciate a link to the original repo or site or something (which you've done), but otherwise I have no issue with it :+1:

**Comment by wjramos** [comment]
@tinalatif Thanks Tina! That's great to hear. I did quite a few last night (not as easy as just reshaping the template, have to manipulate the art quite a bit, and I've been cleaning up the design files quite a bit)

I have to say, some of the icons look pretty amazing round
