### ISSUE TITLE
Icon Revision: Finder

### ISSUE THREAD

**Issue by wjramos** [tinalatif/flat.icns#197]
How would you guys feel about a more minimal Finder icon?

Icon in set:
![finder](https://cloud.githubusercontent.com/assets/5625810/8600020/7871a410-2618-11e5-8780-e27e2a8f75fd.png)

Fully Minimal version:
![finder](https://cloud.githubusercontent.com/assets/5625810/8600011/692431f8-2618-11e5-9911-c8b0cd97d07e.png)

or I could just make the black more washed out

**Comment by mcallinder** [comment]
I like the minimal one a lot. I personally feel the black lines on the other are too bold.

**Comment by tinalatif** [comment]
I agree the black's a little bold. It could be lightened a bit. I think going full minimum strays a bit too far form the original

**Comment by wjramos** [comment]
![finder](https://cloud.githubusercontent.com/assets/5625810/8860567/90cc57cc-3139-11e5-83da-9e92ea895f7b.png)
