### ISSUE TITLE
Revision: Transmit

### ISSUE THREAD

**Issue by wjramos** [tinalatif/flat.icns#217]
Current Icon
![transmit](https://cloud.githubusercontent.com/assets/5625810/8868763/b2687684-3190-11e5-9ff5-13aa6fe80b1c.png)

Proposed Icon
![transmit2](https://cloud.githubusercontent.com/assets/5625810/8868766/beb3ab8e-3190-11e5-8a5a-f23c5b5d99cd.png)

**Comment by mknrls** [comment]
@wjramos really like the new one :D amazing

**Comment by mcallinder** [comment]
I prefer the old one. I don't think the new one fits the set's theme very well.
