### ISSUE TITLE
Icon request: GitX, VirtualBox, pgAdmin3, Wake Up Time

### ISSUE THREAD

**Issue by dbkaplun** [tinalatif/flat.icns#22]

**Comment by mknrls** [comment]
virtualbox icon will be work on by @wjramos 
@secrettriangle do you still need the GitX, pgAdmin3, Wake Up Time icons ?

**Comment by wjramos** [comment]
I actually may try and update the tor icon as well

**Comment by mknrls** [comment]
the tor icon is fine tho, what would like to change about it ?

**Comment by wjramos** [comment]
I feel it doesn't quite match the style of the other icons, I dunno though

**Comment by mknrls** [comment]
naw it fine :P we will take care of it later if needed. Lets take care of all the icons issues first and then we can worry about redoing older icons if necessary

**Comment by secrettriangle** [comment]
Yep, all of 'em: GitX, VirtualBox, pgAdmin3, and Wake Up Time. :stuck_out_tongue: 

Tor icon is fine for now.

**Comment by mknrls** [comment]
oki lol the remaining icons, will be work on in next few days or so :)

**Comment by wjramos** [comment]
For GitX, how do you think it would look after increasing the weight [like this](https://www.kalosflorida.com/wp-content/uploads/2014/03/plus-sign.jpg)?

**Comment by secrettriangle** [comment]
@mknrls that's the right Wake Up Time, yes. Great work so far BTW!

**Comment by mknrls** [comment]
@wjramos a little to bulky, like the icons is using a light font 
@secrettriangle thanks man:) dope

**Comment by wjramos** [comment]
![virtual-box](https://cloud.githubusercontent.com/assets/5625810/7335616/7cd88b04-eb80-11e4-9fd1-0fa9ab50262f.png)

**Comment by wjramos** [comment]
![virtual-box](https://cloud.githubusercontent.com/assets/5625810/7335622/c3b333e4-eb80-11e4-81af-7e92ac09f8e7.png)

**Comment by wjramos** [comment]
I'd like to do the dock preview frame as well, do you happen to know where that icon is located @secrettriangle?

**Comment by secrettriangle** [comment]
@wjramos what do you mean by dock preview frame? Awesome VirtualBox icon!

@mknrls I like the second Wake Up Time better, it's more readable.

**Comment by mknrls** [comment]
@secrettriangle i prefer that one too, happy you like it

**Comment by wjramos** [comment]
![screenshot 2015-04-23 13 54 50](https://cloud.githubusercontent.com/assets/5625810/7338475/d87ed3c4-ec01-11e4-8c6e-ca8c8c9cde9c.png)

**Comment by secrettriangle** [comment]
Hmm, I don't know where the frame is located, but I think it should be fine to improvise.

**Comment by wjramos** [comment]
Also made an alternative Virtual Box 
![virtual-box](https://cloud.githubusercontent.com/assets/5625810/7442587/5ed21610-f0cc-11e4-8bdd-d9af45cec7f7.png)

**Comment by wjramos** [comment]
I'm thinking the first one might be best though

**Comment by tinalatif** [comment]
@secrettriangle GitX, phAdmin and Wake Up Time merged at b7d9d9c15d677f0516cf58268d7aa6d72061a772

@wjramos I actually like the second one better, the frameless look is more in line with some of the other icons

**Comment by secrettriangle** [comment]
I think they're both great. Can we have two icons for the same app in the repo?

**Comment by wjramos** [comment]
I'm open to it, I think it would be up to @tinalatif. Maybe we can set it up with the convention of primary/alternative where the application script would default to the primary, but alternative could be available for manual application

**Comment by tinalatif** [comment]
I don't generally have a problem with two icons for the same app, but in this case, I'd discourage it for the sake of sticking to the theme

**Comment by secrettriangle** [comment]
Can we get a PR for the VirtualBox icons? Then we can close out this issue. :)

**Comment by wjramos** [comment]
Requested :)

**Comment by tinalatif** [comment]
VirtualBox merged at 3b3ea4bb9427ff77a95cc2911e25bcdb92547a70
