### ISSUE TITLE
calendar text are slanted?

### ISSUE THREAD

**Issue by anderson202** [tinalatif/flat.icns#221]
Hi, I manually installed the calendar icon but the text for the dates are slanted. Is this a bug or intended?

**Comment by wjramos** [comment]
It's intended as the default dock widget for Calendar. Included in the pack is a slanted Calendar to act as the base for the widget so the numbers look correct

**Comment by snauhaus** [comment]
@anderson202 is right though, the icon does look strange with the slanted text. Maybe it should be changed to accommodate for the fact that the text isn't straight?

**Comment by wjramos** [comment]
I want to make sure: you are referring to the replacement icon for ![Apple's dock calendar icon](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Art/CalendarY_2x.png)

Which should be ![flat.icns calendar icon](https://github.com/tinalatif/flat.icns/blob/master/pngs/calendar2-empty.png?raw=true)

I don't have Apple calendar installed to verify, but I'd think the month would align in the center of the red, and the date would center in the white

**Comment by snauhaus** [comment]
You're right, my bad. I was using the wrong icon, which I'm guessing is the case for @anderson202 as well.
