### ISSUE TITLE
Icon Request: Facebook Messenger

### ISSUE THREAD

**Issue by josephmilla** [tinalatif/flat.icns#226]
It would be great to have a flat desktop icon for this: http://fbmacmessenger.rsms.me/

**Comment by wjramos** [comment]
Hey @josephmilla - 

I created an icon for FB messenger, for the app Goofy, but it's generic enough to fit any Facebook messenger app (maybe I should rename it to just be Facebook Messenger)

https://github.com/tinalatif/flat.icns/blob/master/pngs/Goofy.png

**Comment by josephmilla** [comment]
@wjramos Looks nice! Thanks!
