### ISSUE TITLE
Steam icon reverts to default when app's running

### ISSUE THREAD

**Issue by sunabozu** [tinalatif/flat.icns#233]
I'm not quite sure if it's appropriate to create this issue here, so excuse me in advance. The title is self-explanatory. After using Liteicon new icon's only visible when Steam isn't running. I tried to replace another icon inside Steam.app, but it didn't work.
Is there a way to make it consistent?

**Comment by wjramos** [comment]
Steam has a sub-application for the main client with a separate icon. The main application addressed by lite icon is the launcher, and to change the client icon, you will have to manually change it in the app's package contents

**Comment by sunabozu** [comment]
Yes, I figured that out and replaced it (in fact,the app stores two instances of that icon). But during each start Steam evidently checks its integrity and in case of such replacement downloads old icons and put them in place.
I even tried to lock those files, but surprisingly it didn't help. Steam somehow shows old icon despite the new one stays untouched. It seems like Valve really likes that round icon.

**Comment by CreatedBySeb** [comment]
It's not about Valve liking or disliking the icon, it's about them wanting to protect the content of Steam by validating every file so that it is correct, and people can't pirate games or cheat in them. You should close this as the author can't do anything about this.
