### ISSUE TITLE
Icon Request: Telegram

### ISSUE THREAD

**Issue by danielsatanik** [tinalatif/flat.icns#246]
https://telegram.org/

**Comment by CreatedBySeb** [comment]
How's this?
![telegram](https://cloud.githubusercontent.com/assets/11736217/16661934/30150b8e-446d-11e6-948f-af0a8d4b57cb.png)

**Comment by danielsatanik** [comment]
Thank you very much it is great :D

**Comment by viktorstrate** [comment]
I have added this icon to my fork if you are interested @danielsatanik, viktorstrate/flat.icns@37c2be9324fdad8626d9d12460518b70b2e80a29
