### ISSUE TITLE
Icon Request: Microsoft Teams

### ISSUE THREAD

**Issue by danielsatanik** [tinalatif/flat.icns#272]
https://products.office.com/en-us/microsoft-teams/group-chat-software

**Comment by viktorstrate** [comment]
![microsoft teams 1024](https://user-images.githubusercontent.com/4233458/29749440-d2f5be1a-8b2b-11e7-87b7-c2babd92069b.png)

I have added this icon to [my fork](https://github.com/viktorstrate/flat.icns)

**Comment by danielsatanik** [comment]
@viktorstrate: May I actually ask how to export from Illustrator to SVG, so that your build script works? I seem not to be able to. E.g. when I try to build the red calender icon myself, the red bar is not cut by the borders like this

![calendar3 256](https://user-images.githubusercontent.com/2507586/31773145-14544446-b4e2-11e7-806b-678800dcc5d6.png)

**Comment by viktorstrate** [comment]
@danielsatanik: If you own Illustrator, you can export to svg under File -> Export. Otherwise you can use Inkscape to open the illustrator files, and then export it to svg that way (File -> Save As -> Optimized SVG).
