### ISSUE TITLE
Icon Request: Insomnia

### ISSUE THREAD

**Issue by danielsatanik** [tinalatif/flat.icns#275]
https://insomnia.rest

**Comment by viktorstrate** [comment]
@danielsatanik I have uploaded an icon to [my fork](https://github.com/viktorstrate/flat.icns)
![icon_1024x1024 2x](https://user-images.githubusercontent.com/4233458/34042558-8b408b36-e19d-11e7-9f4b-62b2dbb2a719.png)

**Comment by danielsatanik** [comment]
damn you are fast :D

**Comment by viktorstrate** [comment]
Yeah, i guess you posted the issue on the right time 😄
