### ISSUE TITLE
Request: Omnigraffle

### ISSUE THREAD

**Issue by jaketame** [tinalatif/flat.icns#278]
I would quite like OmniGraffle :)

Thanks

**Comment by viktorstrate** [comment]
This project have been inactive for over 3 years.
I have therefore made a fork to keep the project alive, [link to my fork](https://github.com/viktorstrate/flat.icns).
Where an icon for Omnigraffle already have been added, along with many more.

**Comment by jaketame** [comment]
Thanks. Missed that!
