### ISSUE TITLE
Icon request: Sourcetree, PivotalBooster

### ISSUE THREAD

**Issue by gokmen** [tinalatif/flat.icns#33]
Web pages: http://www.sourcetreeapp.com/ http://pivotalbooster.com/

**Comment by mknrls** [comment]
Sitll need the PivotalBooster icon ?

**Comment by mknrls** [comment]
@gokmen Sitll need the PivotalBooster icon ?

**Comment by gokmen** [comment]
that's fine, I'm going to close this.
