### ISSUE TITLE
Icon Request: Xamarin Studio

### ISSUE THREAD

**Issue by jamez14** [tinalatif/flat.icns#38]
Xamarin Studio would be great!

Also Xamarin.iOS Build Host would be cool, but I don't want to push it. 

I attached a photo for reference, Xamarin Studio on the left and Build Host on the right
![screen shot 2014-07-22 at 8 59 40 pm](https://cloud.githubusercontent.com/assets/2854919/3667449/a575c4f6-1204-11e4-8a0a-8d58e34ee9a4.png)

**Comment by mknrls** [comment]
@jamez14 still need the Xamarin Studio icon ?

**Comment by jamez14** [comment]
@mknrls if no one else has requested it then I'd say no. I haven't been using Xamarin Studio that much so it has left my dock. Thanks for checking though!

**Comment by mknrls** [comment]
@jamez14 no worry mate,  you can close this issue :)
