### ISSUE TITLE
Icon Request: Sparrow

### ISSUE THREAD

**Issue by LekisS** [tinalatif/flat.icns#39]
Icon for http://sparrowmailapp.com/mac.php

![sparrow](https://cloud.githubusercontent.com/assets/28733/3689296/cc68be5c-133e-11e4-9240-f4202c9481cd.png)

**Comment by wjramos** [comment]
I'd love to do this one, is there still a need for it now that Sparrow is defunct?

**Comment by LekisS** [comment]
Actually I know a lot of people who are still using Sparrow (including me).

**Comment by wjramos** [comment]
![sparrow](https://cloud.githubusercontent.com/assets/5625810/7487934/91ba7a0c-f376-11e4-9498-1448eedf3794.png)
![sparrow2](https://cloud.githubusercontent.com/assets/5625810/7487933/91b8fc2c-f376-11e4-8c29-2f06edefac4f.png)

**Comment by LekisS** [comment]
wow, love it, thanks ;)

**Comment by wjramos** [comment]
Any preference of the two (I'm leaning towards #2)

**Comment by LekisS** [comment]
Me too ;)

**Comment by wjramos** [comment]
Now as far as level of detail, here's one that looks more 'folded'
![sparrow2](https://cloud.githubusercontent.com/assets/5625810/7508474/b6326ee8-f435-11e4-9fc0-5033a39e151a.png)

**Comment by wjramos** [comment]
Slightly more perspective added
![sparrow2](https://cloud.githubusercontent.com/assets/5625810/7508542/eb4fccc8-f436-11e4-91db-be9713fe1a8f.png)

**Comment by LekisS** [comment]
I think I like the 2nd one more.

**Comment by tinalatif** [comment]
Merged at b87af7be98332c912d9bc7a006c42f9e7fcdc485
