### ISSUE TITLE
Icon Request: League of legends

### ISSUE THREAD

**Issue by mwdavies** [tinalatif/flat.icns#48]
Love the dock! Just need this one! 

http://th08.deviantart.net/fs51/150/f/2009/265/8/f/League_Of_Legends_by_DKman.png

Thanks!!!

**Comment by wjramos** [comment]
@dennistimmermann I'm also a fan of #2 -- I think you can go ahead and issue a pull request with the files if you are still around

**Comment by wjramos** [comment]
![lol](https://cloud.githubusercontent.com/assets/5625810/7335711/247c1cd2-eb85-11e4-811f-7fc1a55dfe9a.png)

**Comment by wjramos** [comment]
![lol](https://cloud.githubusercontent.com/assets/5625810/7335751/dee390e4-eb87-11e4-8765-3211aef24728.png)
I made a new copy

**Comment by tinalatif** [comment]
This has been merged: 76b24a6e2db7d1af7426e0f51c77a16ddf5d9231
