### ISSUE TITLE
Icon Request: Adobe Lightroom

### ISSUE THREAD

**Issue by Traiteur** [tinalatif/flat.icns#49]
The only two Adobe programs that I constantly use are Photoshop and Lightroom, and you've made an amazing Photoshop icon, so it'd be awesome if you could make a Lightroom one as well. :)

**Comment by wjramos** [comment]
Added #205

**Comment by tinalatif** [comment]
Merged at 48d697c849940963f9a105639f8d8cbc8da975e7
