### ISSUE TITLE
Icon request: Zotero

### ISSUE THREAD

**Issue by tinalatif** [tinalatif/flat.icns#56]

**Comment by mknrls** [comment]
@tinalatif do you still need this icon?

**Comment by tinalatif** [comment]
This is a placeholder for a request made elsewhere (probably Twitter) which never got filled

**Comment by mknrls** [comment]
now it is ;P witch one you like better? 
![zotero_preview](https://cloud.githubusercontent.com/assets/6585299/7265747/cb152212-e86c-11e4-871c-d5e2ee563a8c.png)

**Comment by tinalatif** [comment]
woohoo!
I'd personally go with the top-right one because it fits the original logo the best

**Comment by mknrls** [comment]
cool :)

**Comment by wjramos** [comment]
I also like top right the best

**Comment by mknrls** [comment]
i think we close this issue to :) i will be added to the merge in a few days or so

**Comment by tinalatif** [comment]
Merged: b7d9d9c15d677f0516cf58268d7aa6d72061a772
