### ISSUE TITLE
Icon Request: ProCSSor

### ISSUE THREAD

**Issue by bluetidepro** [tinalatif/flat.icns#62]
app url: http://procssorapp.com/

**Comment by mknrls** [comment]
@bluetidepro still neeed this icon ?

**Comment by wjramos** [comment]
App *appears* defunct as it hasn't been updated since 2012

**Comment by mknrls** [comment]
that what i was thinking, and since then they have been some new  tools for theses

**Comment by bluetidepro** [comment]
@wjramos @mknrls Yeah, no worries, we can close it out :)
