### ISSUE TITLE
Icon Request: CodeKit

### ISSUE THREAD

**Issue by bluetidepro** [tinalatif/flat.icns#63]
app url: https://incident57.com/codekit/

**Comment by wjramos** [comment]
![codekit](https://cloud.githubusercontent.com/assets/5625810/6763479/141a3cee-cf3c-11e4-8970-0fac3c861d19.png)

**Comment by coltonfitzgerald** [comment]
Is it just me or is this icon a different size compared to all of the other icons? When I apply this one and its sitting on my dock it looks bigger.

**Comment by wjramos** [comment]
Let me take a look, that should only happen if I exported it differently than usual

**Comment by wjramos** [comment]
I want to make sure, was that the .icns or .png?

**Comment by wjramos** [comment]
![screenshot 2015-04-19 21 35 43](https://cloud.githubusercontent.com/assets/5625810/7223741/153ba09c-e6dc-11e4-846a-cf28ae8be510.png)

**Comment by coltonfitzgerald** [comment]
![screenshot 2015-04-19 21 38 30](https://cloud.githubusercontent.com/assets/2644431/7223766/8074da5e-e6dc-11e4-9eb9-0c76ca7faac7.png)
I took the .png that you attached to this issue and converted it to a .icns

**Comment by coltonfitzgerald** [comment]
Nvm, I fixed it

**Comment by wjramos** [comment]
Oh! You may want to grab the copy in the latest version of the icon pack

**Comment by mknrls** [comment]
issue can be close ;)

**Comment by tinalatif** [comment]
Merged: a16c2ce24bea65e9ad677ee8d733c624b4060dc4
