### ISSUE TITLE
Icon Request: Dash

### ISSUE THREAD

**Issue by bluetidepro** [tinalatif/flat.icns#64]
url: http://kapeli.com/dash

**Comment by wjramos** [comment]
I'll take a crack at this one tonight

**Comment by wjramos** [comment]
![dash](https://cloud.githubusercontent.com/assets/5625810/6819239/fe61cc5e-d27a-11e4-9237-1069d3394767.png)
![dash2](https://cloud.githubusercontent.com/assets/5625810/6819240/fe63faba-d27a-11e4-9de9-b820ea91d0c0.png)

**Comment by wjramos** [comment]
![dash](https://cloud.githubusercontent.com/assets/5625810/6831882/6000a18c-d2e0-11e4-97c7-d66a90f2e7cf.png)

**Comment by mknrls** [comment]
Been added to repo. Issue can be close

**Comment by tinalatif** [comment]
Merged: 7630c9dd96fd40f07a738b162e0115037e51a7a7
