### ISSUE TITLE
Icon Request: VOX

### ISSUE THREAD

**Issue by WayneSan** [tinalatif/flat.icns#66]
URL: http://coppertino.com/vox/osx/

**Comment by mknrls** [comment]
@WayneSan still need an icon for this?

**Comment by wjramos** [comment]
![vox](https://cloud.githubusercontent.com/assets/5625810/7301889/5b23ae0e-e99a-11e4-97a7-bc510efb9815.png)
First draft, any ideas?

**Comment by mknrls** [comment]
Look good to me man.

**Comment by wjramos** [comment]
I'll issue a request in a little while

**Comment by tinalatif** [comment]
Merged: a256977e3c099324cb48d45a9f110ddb17b01a2e
