### ISSUE TITLE
Icon Request: The Unarchiver

### ISSUE THREAD

**Issue by kudlajz** [tinalatif/flat.icns#67]
http://wakaba.c3.cx/s/apps/unarchiver

Thanks!

**Comment by TheQuantum** [comment]
+1

**Comment by wjramos** [comment]
+1

**Comment by wjramos** [comment]
First attempt 

![Unarchiver](https://github.com/wjramos/flat.icns/blob/unarchiver/pngs/unarchiver.png)

**Comment by TheQuantum** [comment]
Ha! Agreed, but I think the one you made does a good job of combining Unarchiver's style with flat.icns.  I don’t have any suggestions.

**Comment by mknrls** [comment]
Been added to the repo. Issue can be closed

**Comment by tinalatif** [comment]
Merged: c8adf41091696c116e7ee18b5c2bb56f9ca1524f
