### ISSUE TITLE
icon request: clear

### ISSUE THREAD

**Issue by AO16** [tinalatif/flat.icns#69]
http://realmacsoftware.com/clear

**Comment by balazsfeher** [comment]
+1

**Comment by wjramos** [comment]
![things](https://cloud.githubusercontent.com/assets/5625810/7221622/5d99ced0-e6a6-11e4-9e66-60badff2d3c1.png)
![things2](https://cloud.githubusercontent.com/assets/5625810/7221621/5d983c64-e6a6-11e4-8bf9-519ecb82c56a.png)

**Comment by mknrls** [comment]
been added to the repo. issue can be close

**Comment by AO16** [comment]
Thanks!
