### ISSUE TITLE
Icon Request: Unity & MonoDevelop

### ISSUE THREAD

**Issue by tpai** [tinalatif/flat.icns#72]
http://unity3d.com

http://www.monodevelop.com/

looking forward to it! ;)

**Comment by mknrls** [comment]
these icons will be work on in next few days or so.

**Comment by mknrls** [comment]
@tpai let me know if there's any improvement that have to be made, 
if not these icons will be added to the repo in the next few days. Thanks :)

![unity](https://cloud.githubusercontent.com/assets/6585299/7339273/36e00a66-ec37-11e4-8fe9-cb278328add8.png)

![monodevelop](https://cloud.githubusercontent.com/assets/6585299/7339274/3d6d8d22-ec37-11e4-9e05-5f1f6ebf04b5.png)

**Comment by tinalatif** [comment]
Merged at b7d9d9c15d677f0516cf58268d7aa6d72061a772

**Comment by tpai** [comment]
Sorry for delayed response, these two icon seems awesome! You did a great job! :)

**Comment by mknrls** [comment]
@tpai thanks :)
