### ISSUE TITLE
Icon Request: Adobe Lightroom

### ISSUE THREAD

**Issue by balazsfeher** [tinalatif/flat.icns#73]
https://lightroom.adobe.com/

**Comment by wjramos** [comment]
![adobe-lightroom](https://cloud.githubusercontent.com/assets/5625810/7442580/e791d5ea-f0cb-11e4-976a-bba5b867e8e9.png)

**Comment by balazsfeher** [comment]
Great one!

**Comment by wjramos** [comment]
Added #205

**Comment by tinalatif** [comment]
Merged at 48d697c849940963f9a105639f8d8cbc8da975e7
