### ISSUE TITLE
Icon Requests: Grapher, iTerm, BetterSnapTool

### ISSUE THREAD

**Issue by myurtoglu** [tinalatif/flat.icns#74]
Here are the current icons: 

- [Grapher](http://en.wikipedia.org/wiki/Grapher#/media/File:Grapher_icon.png)
- [iTerm](http://www.devspaper.com/wp-content/uploads/2014/07/Snip20140716_16.png)
- [BetterSnapTool](http://blog.boastr.net/bsticon.png)

Thank you very much!

**Comment by wjramos** [comment]
![iterm](https://cloud.githubusercontent.com/assets/5625810/6746456/b1ab188c-ce85-11e4-94e6-055c5deb6bb2.png)

**Comment by myurtoglu** [comment]
Cool!

**Comment by wjramos** [comment]
![bettersnaptool](https://cloud.githubusercontent.com/assets/5625810/6747081/1c859a8c-ce91-11e4-9e89-701c7df6b6a2.png)
Do you think it needs the buttons?

**Comment by wjramos** [comment]
![bettersnaptool](https://cloud.githubusercontent.com/assets/5625810/6747141/1b83e962-ce92-11e4-9cdf-76593c776404.png)

**Comment by wjramos** [comment]
Here's some attempts at Grapher:

![grapher1](https://cloud.githubusercontent.com/assets/5625810/6747310/b990e8b0-ce94-11e4-93cb-3cc140f8c9d3.png)
![grapher2](https://cloud.githubusercontent.com/assets/5625810/6747311/b9917cda-ce94-11e4-991d-9b559fac6a36.png)
![grapher3](https://cloud.githubusercontent.com/assets/5625810/6747312/b995f3d2-ce94-11e4-87ee-a0145f657004.png)

**Comment by myurtoglu** [comment]
Great work thank you! I am starting to use these now. Also, for the grapher, I just found [this icon](http://www.macupdate.com/images/icons256/20194.png), from [this app](http://www.macupdate.com/app/mac/20194/plot). Maybe something like this with your color patterns would be nice?

Thanks again!

**Comment by wjramos** [comment]
Here's one more similar to the OSX icon for it - ![grapher3](https://cloud.githubusercontent.com/assets/5625810/6772191/1603fc3c-d0b5-11e4-931d-7d7768306b03.png)
I'll be working on an alternative style that follows the same color scheme but a different style

**Comment by myurtoglu** [comment]
@wjramos great icons for grapher!

**Comment by wjramos** [comment]
Of the ones posted, any preference?

**Comment by TheQuantum** [comment]
Of the one’s you’ve posted so far, I’d say I like the first perspective hexagon (with the wider color ribbon).  I think the ribbon needs to be a bit larger though to really fit in with the other apps.  Maybe if you dropped the darker hexagon and just enlarged the ribbon?

**Comment by myurtoglu** [comment]
@wjramos I liked the first two of your latest grapher icons most. I agree with @TheQuantum, dropping the darker hexagon may make things better.

**Comment by wjramos** [comment]
![graphe6](https://cloud.githubusercontent.com/assets/5625810/6808876/f3dd36cc-d213-11e4-9224-191fea4ae982.png)
The grey looks a little strange now so I tried one with a stark white background as well
![grapher7](https://cloud.githubusercontent.com/assets/5625810/6808903/1f92ed66-d214-11e4-817b-7e907ecc0190.png)

**Comment by wjramos** [comment]
What do you guys think? Should I try out some other ideas or submit a pull request?

**Comment by myurtoglu** [comment]
@wjramos I liked all your work so far, I am away from my mac for a few days but I liked the first and the last (with blue hexagon) most in your last post. It may be time to submit a pull request indeed!

**Comment by TheQuantum** [comment]
The blue hexagon is my favorite and looks great in launchpad/on my dock.  I’d submit a pull request with that one.

**Comment by wjramos** [comment]
This issue can be closed

**Comment by myurtoglu** [comment]
Closing, thanks!
