### ISSUE TITLE
Icon Reqs - Icon Box, TweetBot, Adium, MacVim, Linkinus (chat icon)

### ISSUE THREAD

**Issue by imajes** [tinalatif/flat.icns#8]
Hey-

specific as mentioned, but wondered if we could get a set of generic set - chat, edit, etc?

**Comment by mknrls** [comment]
@imajes do you still need the the remaining icons?

**Comment by wjramos** [comment]
Adium is already in the pack, I think tweetbot would be a good one to add

**Comment by imajes** [comment]
Link would be good. To be honest though, for some of these apps, i've used
alternate icons because the original ones are not very aesthetically
pleasing, so even making them flat would not be an improvement :P

best
james

On Wed, Apr 22, 2015 at 9:46 AM, Jordan Ramos <notifications@github.com>
wrote:

> Adium is already in the pack, I think tweetbot would be a good one to add
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tinalatif/flat.icns/issues/8#issuecomment-95260533>.
>



-- 
James Cox,
Consultant, Raconteur, Photographer, Entrepreneur
t: +1 347 433 0567  e: james@imaj.es w: http://imaj.es/
talk: http://twitter.com/imajes photos: http://500px.com/imajes

**Comment by mknrls** [comment]
guess we could do Link and tweetbot, then close this issue :) 
You never know, we could maybe convince you otherwise. 
These icons will be work on in next few days or so.

**Comment by mknrls** [comment]
@imajes so i did tweetbox but as for Linkinus do you think is still needed, don't think the app is still being develop anymore and they no longer have a website. 
 
![tweetbot](https://cloud.githubusercontent.com/assets/6585299/7439414/5dff9a48-f048-11e4-9b72-9829384be60d.png)

**Comment by wjramos** [comment]
Think this is good to close

**Comment by tinalatif** [comment]
@wjramos Icon Box is missing so I don't know how I feel about closing the issue. But the original icon is such a mess that I don't even know what direction to go in...

**Comment by mknrls** [comment]
yeah Icon Box is one crazy icon lol i was trying to avoid it for now and see if you or @wjramos would like to do it ahah, i might try it tho and see what i can come up with

**Comment by wjramos** [comment]
I think Icon Box is no longer supported

**Comment by wjramos** [comment]
If that's not the case I'd gladly take a crack at it

**Comment by wjramos** [comment]
![Iconbox](https://trello-attachments.s3.amazonaws.com/554b04cafba5ad74664ee54b/1024x1024/499fba7e8780484100be54245bb89a5f/iconbox.png)

**Comment by tinalatif** [comment]
@wjramos Well done!! My only (optional) suggestions: make the white row heights match the blue rows (so they don't have the little top ledge where they meet)

**Comment by wjramos** [comment]
PR issued #203 

I decided to leave the little visual misalignment.
The grey between the white panels is a gap. With the shelves, the grey is the edge of a shelf (indicated by green light). The panels are then covering the contents of the shelf

**Comment by tinalatif** [comment]
Merged at 651c913e18ad2fec8331323a4f4071d1f983b22a
Woohoo!
