### ISSUE TITLE
Issue: Fix Calendar Update

### ISSUE THREAD

**Issue by jlina09640** [tinalatif/flat.icns#99]
For some reason the Calendar app won't update on my dock or in my launchpad. Tried using LiteIcon to replace it, wouldn't work, no matter which icon I used, no matter how many times I restart my computer.

For some reason, it only updates my icon when I got directly to Applications through Finder. I tried removing Calendar from my dock in hopes that it will update, but no luck. My friend is having the same issue as well. This definitely needs to be fixed or at least better documented.

**Comment by TasyaHarrington** [comment]
I have this same issue with a couple apps. Every app that has this issue has what I personally call a dynamic icon. The calendar app changes daily with the day's date. I have a weather app that updates with the temperature and current conditions. In the applications folder each app has the icon I assigned, but in the dock they don't. I have yet to find a way to fix this.

**Comment by jlina09640** [comment]
I had a feeling that the issue behind it is the fact that it changes dynamically in the dock, but it's definitely an issue we should fix. What other apps have you found also have this problem, other than the weather app?

**Comment by jlina09640** [comment]
Actually I got it to work for the calender, I'll issue a pull request for it.
